{% set name = "sushy" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 16e6cddc34e533bf9628905db87c9411b75318e74deecdb2f91afee93c5bff56

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pbr !=2.1.0,>=2.0.0
    - pbr
    - python
  run:
    - pbr !=2.1.0,>=2.0.0
    - python
    - python-dateutil >=2.7.0
    - requests >=2.14.2
    - six >=1.10.0
    - stevedore >=1.29.0

test:
  imports:
    - sushy
    - sushy.auth
    - sushy.connector
    - sushy.exceptions
    - sushy.main
    - sushy.utils

about:
  home: https://github.com/openstack/sushy
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: Sushy is a Python library to communicate with Redfish based systems. The goal of the library is to be extremely simple, small, have as few dependencies as possible and be very conservative when dealing with BMCs by issuing just enough requests to it (BMCs are very flaky).

extra:
  recipe-maintainers:
    - pg-hbk
    - sy-hbk
