travis:
  secure:
    BINSTAR_TOKEN: HjlgwsZ+a/CbFNuy+TBqqKSKhd5lqPcy4LJphmk1BOSRcms3e4JvYk8Eg4FlP+sheoEndYgveykCZYAM7W5i1t3vxVP6LASbFm5vTCucAWuOruRHvXw2hupIKD+8xm7jWFrm2g8YNw33HDQifzJGZ3pawTd9Nfs5eI9BGVtKGvqQ6QUT5FtuiHc3QKqeWwbja/BrmGoMKB/ImzGBxzxSq110FGE9nFy1WlMvd2JakawC7Qsk0jVIuHN4u8HZ3eI+0hYH3/YXVsXyw7JCf11Wf8MsKVWgwpb7iG56i7TXmR8a4FvwuaqqIhjb1O4IJCnAoOTibFPcGOtQVNZV8MRy8IhYW6GMTdloH/ToaA83oeFkbQuan6zZ0pBiZ2V3qUOcPjxDkx6uMHPnZPZiTREnzF5w2xW44RzbSL1uG9/meDyagEVg22FZzVRVNI0uc44C9ZJa2i2SflVBjxGUx4+oboi+I65efj/ULvZrcl+LKkd6ZUVlZSjOCTriPJbNZXCXAgecqMKDmHkRPvAVwWjOlB5Lpmkv2/ObIIFY+p4+Zc1tIdVs13xuaY6K7D0GVXKwZUcSYWs5q9erOKn9uNxrF7AiakvjeATX3h0EiJv+/xxnnF9Lkftz4OYAF+Rvb0bPpL3jQCV3WDUeVgdBxoPn0AV5z8f07DAqfWrolVhMfiw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
